# Generated by Django 6.0.5 on 2026-05-16 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBaju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('asal_daerah', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga_dasar', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_penyewa', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=30, unique=True)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=2)),
                ('tanggal_daftar', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UkuranBaju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ukuran', models.CharField(max_length=10)),
                ('lingkar_dada', models.FloatField()),
                ('panjang_baju', models.FloatField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BajuNikah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_baju', models.CharField(max_length=100)),
                ('warna', models.CharField(max_length=50)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('harga_sewa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kondisi', models.CharField(choices=[('BAIK', 'BAIK'), ('CUKUP', 'CUKUP'), ('RUSAK', 'RUSAK')], default='BAIK', max_length=20)),
                ('deskripsi', models.TextField()),
                ('foto_baju', models.ImageField(blank=True, null=True, upload_to='baju/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_baju_nikah_app.kategoribaju')),
                ('ukuran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_baju_nikah_app.ukuranbaju')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMINISTRATOR'), ('KASIR', 'KASIR'), ('USER', 'USER')], default='USER', max_length=20)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=2)),
                ('foto_profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransaksiSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_transaksi', models.CharField(max_length=50, unique=True)),
                ('tanggal_sewa', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('lama_sewa', models.PositiveIntegerField()),
                ('total_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_sewa', models.CharField(choices=[('DIPROSES', 'DIPROSES'), ('DISEWA', 'DISEWA'), ('DIKEMBALIKAN', 'DIKEMBALIKAN'), ('SELESAI', 'SELESAI')], default='DIPROSES', max_length=30)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_baju_nikah_app.penyewa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('diterima_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sewa_baju_nikah_app.transaksisewa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksiSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(choices=[('AKTIF', 'AKTIF'), ('NONAKTIF', 'NONAKTIF')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('harga_sewa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('baju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_baju_nikah_app.bajunikah')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_transaksi', to='sewa_baju_nikah_app.transaksisewa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
