# Generated by Django 6.0.5 on 2026-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_baju_nikah_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ukuranbaju',
            old_name='berat_badan',
            new_name='rekomendasi_berat_badan',
        ),
        migrations.RenameField(
            model_name='ukuranbaju',
            old_name='tinggi_badan',
            new_name='rekomendasi_tinggi_badan',
        ),
        migrations.AddField(
            model_name='bajunikah',
            name='status_ketersediaan',
            field=models.CharField(choices=[('TERSEDIA', 'TERSEDIA'), ('TIDAK_TERSEDIA', 'TIDAK_TERSEDIA')], default='TERSEDIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='bajunikah',
            name='stok',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
