# Generated by Django 6.0.5 on 2026-05-16 09:47

import sewa_baju_nikah_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_baju_nikah_app', '0002_rename_berat_badan_ukuranbaju_rekomendasi_berat_badan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajunikah',
            name='foto_baju',
            field=models.ImageField(blank=True, null=True, upload_to=sewa_baju_nikah_app.models.upload_foto_baju),
        ),
    ]
