# Generated by Django 6.0.5 on 2026-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_baju_nikah_app', '0003_alter_bajunikah_foto_baju'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksisewa',
            name='tanggal_dikembalikan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
