# Generated by Django 6.0.5 on 2026-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_baju_nikah_app', '0004_transaksisewa_tanggal_dikembalikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksisewa',
            name='status_sewa',
            field=models.CharField(choices=[('DIPROSES', 'DIPROSES'), ('DISEWA', 'DISEWA'), ('DIKEMBALIKAN', 'DIKEMBALIKAN'), ('SELESAI', 'SELESAI'), ('DIBATALKAN', 'DIBATALKAN')], default='DIPROSES', max_length=30),
        ),
    ]
